DROP TABLE IF EXISTS dogs;

CREATE TABLE dogs (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    breed TEXT NOT NULL,
    age INT NOT NULL
);

DROP TABLE IF EXISTS cats;

CREATE TABLE cats (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    breed TEXT NOT NULL,
    age INT NOT NULL
);

DROP TABLE IF EXISTS phones;

CREATE TABLE phones (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    cost TEXT NOT NULL
);

DROP TABLE IF EXISTS computers;

CREATE TABLE computers (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    cost TEXT NOT NULL
);

DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    singer TEXT NOT NULL,
    producer TEXT NOT NULL,
    album TEXT NOT NULL
);
